docs/development.md

I included everything on macOS and tried to remember the most important parts of the Linux setup. However, I didn't test these yet so please verify them.

Add instructions on setting up Nomad for Poseidon

---

.github/workflows/ci.yml

This PR checks out the code in order to perform the privy analysis. Without our code, the analysis doesn't make much sense, right?

Checkout code for trivy analysis

---

api/swagger.yaml
configuration.example.yaml
internal/api/api.go

Add route for version information

---

internal/api/websocket.go
internal/runner/runner.go

Stop stdout & stderr after timeout

---

api/swagger.yaml
internal/api/api.go
internal/environment/environment.go
internal/environment/manager.go
internal/environment/manager_mock.go
internal/runner/execution_environment_mock.go
internal/runner/manager.go
internal/runner/manager_mock.go
internal/runner/storage.go
pkg/dto/dto.go

Closes #24
Please push me if you see a use case for an additional test ;)

Add statistics route for execution environments

---

internal/nomad/nomad.go

Catch the "Close normal" error

---

cmd/poseidon/main.go
internal/runner/runner_test.go
tests/e2e/websocket_test.go

Improve test reliability

---

internal/api/runners.go
internal/api/runners_test.go

Because some clients fail receiving a response before the body is sent entirely. See https://github.com/openHPI/poseidon/issues/54
As discussed, we think that Poseidon is behaving correctly so far. However, in order to easily solve the problem, we simply read the body before we respond.
Closes #54

Fix early write

---

.github/workflows/ci.yml
api/swagger.yaml
docs/resources/server.example.hcl
internal/environment/nomad_environment.go
internal/environment/template-environment-job.hcl
tests/e2e/e2e_test.go
tests/e2e/environments_test.go
tests/e2e/websocket_test.go

We have to update the Nomad configuration file (staging / prod)
Fixes second task of #43

Enable memory oversubscription

---

deploy/aws/java11Exec/src/main/java/poseidon/App.java
deploy/aws/java11Exec/src/main/java/poseidon/SimpleMakefile.java
deploy/aws/java11Exec/src/test/java/poseidon/AppTest.java
deploy/aws/java11Exec/src/test/java/poseidon/SimpleMakefileTest.java

As the AWS Linux images do not contain make.

Add limited support for Makefile parsing.

---

.github/workflows/docker-image.yml
.golangci.yaml

in the ci build docker image step.

Temporarily fixed golang version mismatch

---

deploy/aws/java11Exec/src/main/java/poseidon/SimpleMakefile.java
deploy/aws/java11Exec/src/test/java/poseidon/SimpleMakefileTest.java
internal/runner/aws_runner.go

Since CodeOcean may send the `\r\n` newline.

Allow the CR character as part of a newline.

---

deploy/aws/java11Exec/src/main/java/poseidon/SimpleMakefile.java
deploy/aws/java11Exec/src/test/java/poseidon/SimpleMakefileTest.java

Ignore @ Symbols in Makefiles

---

deploy/aws/java11Exec/src/main/java/poseidon/App.java
deploy/aws/java11Exec/src/test/java/poseidon/AppTest.java

Add the missing newline of AWS.

---

deploy/aws/java11Exec/src/main/java/poseidon/App.java
deploy/aws/java11Exec/src/test/java/poseidon/AppTest.java

Java11Exec: Fix that EOF is replaced by newline.

---

deploy/aws/java11Exec/pom.xml
deploy/aws/java11Exec/src/main/java/poseidon/SimpleMakefile.java

Java11Exec: Quick fix for test dependencies.

---

deploy/aws/java11Exec/src/main/java/poseidon/SimpleMakefile.java
deploy/aws/java11Exec/src/test/java/poseidon/SimpleMakefileTest.java

Java11Exec: Add support for make assignments.

---

.codeclimate.yml
.github/workflows/ci.yml
README.md
tests/helpers/test_helpers.go

Introduce CodeClimate
to make the test coverage easily accessible.
Closes #105

Coverage report

---

configuration.example.yaml
internal/config/config.go
internal/config/config_test.go
internal/environment/aws_manager.go
internal/environment/aws_manager_test.go
tests/e2e/e2e_test.go
tests/e2e/environments_test.go

to conform with the yaml standard of list definition.
Closes #95

Specify AWS Functions as list

---

internal/api/websocket.go

#155 Add log statement for further investigations

---

internal/runner/nomad_runner.go

#42 Allow deletion of ./*

---

internal/api/websocket.go

In the first commit we moved the condition check of the internal status of the WebSocket connection.
When closing the WebSocket connection after an execution...
https://github.com/openHPI/poseidon/blob/79dc3a94daf62f3b6301246fe20935e916a5553c/internal/api/websocket.go#L268
https://github.com/openHPI/poseidon/blob/79dc3a94daf62f3b6301246fe20935e916a5553c/internal/api/websocket.go#L292-L295
...we send the closing message after we closed the WebSocket connection.
But, when we first send the close message
https://github.com/openHPI/poseidon/blob/79dc3a94daf62f3b6301246fe20935e916a5553c/internal/api/websocket.go#L300
before stopping the WebSocket read internally. We receive errors on the tcp level. Therefore we had to introduce the option to stop the WebSocket reading separately before closing …

#155 Minimise timing issues with websocket close.

---

deploy/aws/java11Exec/src/main/java/poseidon/App.java
deploy/aws/java11Exec/src/main/java/poseidon/SimpleMakefile.java
deploy/aws/java11Exec/src/test/java/poseidon/AppTest.java
deploy/aws/java11Exec/src/test/java/poseidon/SimpleMakefileTest.java
tests/e2e/runners_test.go
tests/e2e/websocket_test.go

as with #147 a new unset command part is introduced.
Also add a regression e2e test that would have caught this issue.
Closes #166

#166 Adjust outdated make command pattern

---

deploy/aws/java11Exec/pom.xml

A small dependency update for Java

Update dependencies in Java POM

---

.golangci.yaml
internal/environment/nomad_manager.go

See [current warnings](https://github.com/openHPI/poseidon/actions/runs/2816106596)

Fix linter issues in GitHub action pipeline

---

deploy/grafana-dashboard/main.json
internal/environment/nomad_environment.go
internal/environment/nomad_manager.go
internal/runner/abstract_manager.go
internal/runner/aws_runner.go
internal/runner/execution_environment.go
internal/runner/nomad_runner.go
internal/runner/runner.go
pkg/storage/storage.go
pkg/storage/storage_test.go

Closes #110 
The open ToDo's of #110 seem to be implemented. What do you think?

#110 Add Grafana dashboard visualizing important Poseidon stats.

---

pkg/storage/storage.go

Since we closed #178 we can remove this log statement that is producing a massive amount of log entries.

Remove monitoring debug statement.

---

docs/configuration.md

Closes #3
The list is based on the first ideation we started during our meeting and some code searches. Please have a look whether everything is correct or whether we need to add more commands.

Specify requirements for Docker images

---

tests/e2e/e2e_test.go
tests/helpers/test_helpers.go

Fix flaky e2e tests because of no idle runners at startup

---

api/swagger.yaml

OpenAPI Add token and version prefix.

---

tests/e2e/e2e_test.go
tests/e2e/environments_test.go

by decreasing the reservation amount.
Closes #220

Fix e2e test exhausted cpu

---

internal/runner/nomad_runner.go
pkg/monitoring/influxdb2_middleware.go
pkg/nullio/content_length.go

> I would propose to additionally extend the ContentLengthWriter (a small bit) to monitor the expected content length and actual length?!
See #239

Monitor file download.

---

.github/workflows/python-ci.yml
deploy/grafana-dashboard/.gitignore
deploy/grafana-dashboard/main.py
deploy/grafana-dashboard/panels/availability_row.py
deploy/grafana-dashboard/panels/general_row.py
deploy/grafana-dashboard/panels/poseidon.dashboard.py
deploy/grafana-dashboard/panels/runner_insights_row.py
deploy/grafana-dashboard/utils/utils.py
deploy/grafana-dashboard/utils/variables.py

This PR is an addition to #200:
- Add some more `maxDataPoints` to the graphs
- Apply `lineInterpolation` to some graphs
- Limit `decimals` to 2
- Fix `.gitignore` (it didn't recognise the file on my system otherwise)
- Always add a comma after each line in methods (it was not unified before)
- Transform strings from single-quotes to double-quotes (it was not unified before)
- Add a Python CI pipeline to generate the dashboard

Add comments to PR #200

---

api/swagger.yaml
docs/configuration.md
internal/api/runners.go
internal/api/runners_test.go
internal/nomad/nomad.go
internal/nomad/nomad_test.go
internal/runner/aws_runner_test.go
pkg/dto/dto.go
tests/e2e/websocket_test.go

Closes #41 
... from the user environment.
Also refactor wrapping with "sh", "-c".

Hide Nomad specific environment variables

---

.gitmodules
internal/environment/template-environment-job.hcl

Related to #82
> Did I integrate everything from our playbooks you created previously? (I used them as a base for the ones I create)
Yes. The new playbooks are great! I learned a lot about how structured playbooks can be :star_struck:

Change to new ansible deployment process

---

docs/nomad_usage.md

Document the container updater mechanism.

---

.gitignore
Makefile
cmd/poseidon/main.go
configuration.example.yaml
internal/config/config.go

Using PGO (Profile-Guided Optimizations), we can potentially improve the overall performance of Poseidon.
See https://go.dev/doc/pgo

Enable profiler and profile-guided builds

---

pkg/monitoring/influxdb2_middleware.go

Previously, we always logged the error on first failure and (nevertheless) tried to send the data within 3 minutes (default configuration).
Fixes POSEIDON-1H
Closes #262

Actual retry sending InfluxDB data

---

cmd/poseidon/main.go

Related to #328 
Our Sentry panic handler was never called as the panic is thrown in a separate goroutine [[1]](https://stackoverflow.com/questions/46230973/how-to-recover-from-an-asynchronous-panic-in-external-package) [[2]](https://go.dev/blog/defer-panic-and-recover).
By moving the recovery functionality in the main goroutine, now panics are captured as Sentry events.

Fix Panic Recovery

---

internal/nomad/api_querier.go
internal/nomad/nomad.go
internal/runner/nomad_manager.go

Related to #358
Automatic merge and deployment this night

Add log statement for handling allocation events

---

pkg/util/util.go
tests/helpers/test_helpers.go

that appeared due to the new version v1.53.1.

Fix golangci-lint errors

---

pkg/monitoring/influxdb2_middleware.go

Degrade InfluxDB Retry Write log

---

internal/config/config.go
pkg/logging/sentry_hook.go

for logs containing errors.
Closes #58

Add Sentry Stack Traces

---

internal/runner/nomad_runner.go
internal/runner/nomad_runner_test.go

As we've already discussed, we want to reuse rescheduled (formerly used) runners, as they are in a clean state. While we do so for `OOM Killed` allocations (see 6a1677dea090e62815e830dd08dcef9baf494669), we did not for other rescheduled allocations. [The case of runner](https://github.com/openHPI/poseidon/files/12643430/poseidonLog.txt) `29-f5d671f7-5316-11ee-af32-fa163e079f19` made this clear.

Reuse rescheduled allocations

---

cmd/poseidon/main.go
configuration.example.yaml
internal/config/config.go

Closes #452 
by extracting the interval and threshold into configuration options.
Related to f670b07e.

Formalize Memory Monitoring

---

internal/runner/nomad_runner.go

Related to #436 
Normally, the result of executing the `lsCommand` should never be empty. However, we have observed that CodeOcean sometimes receives an empty JSON result if the runner is being deleted while the list file system request is processed. Therefore, we add a check if something has been written to CodeOcean and otherwise report an error.
This check does not fix this issue but confirms whether we deal with an empty result of the Nomad execution.

Add error for empty list file system execution.

---

tests/e2e/websocket_test.go

Closes #348 
Our initial matrix test showed a failure ratio of 6% with only one test being flaky:
We will first fix this test and then further investigate other flaky tests mentioned in #348.

Fix flaky e2e tests

---

internal/environment/nomad_manager.go

Remove misleading warning.

---

internal/nomad/nomad.go

Rephrase Evaluation channel log statement.

---

pkg/logging/logging.go

This reverts commit ae86b1c261f6332a8d07458803c47ab7010a1d6b.
This PR should be merged when the investigations of #541 are done.

Revert "Debug HTTPLoggingMiddleware latency."

---

cmd/poseidon/main.go

Closes #598 
that led to missing runners when Nomad created runners faster than the recovery process takes.
By starting the Event Stream not after, but with the start of the runner recovery, Poseidon can register the runners started in the recovery process.

Fix Nomad runner recovery

---

internal/nomad/api_querier.go

Resolves #590 
This time, I checked it's working 🚀

Fix Group Sentry issue

---

internal/environment/nomad_manager.go
internal/nomad/api_querier.go
pkg/logging/sentry_hook.go

that contains both Environment Recovery Errors and Runner Recovery Errors.
Related to #650

Ungroup Sentry Error

---

internal/runner/nomad_manager.go
internal/runner/nomad_manager_test.go

Log unexpectedly stopped environments

---

cmd/poseidon/main.go

Catch unsupported Systemd Watchdog
