openHPI/poseidon

configuration.example.yaml
docs/security.md
internal/api/auth/auth.go

as the use of headers starting with X- has been deprecated in RFC6648.

Change authorization header key

---

.github/auto-merge.yml
.github/dependabot.yml
.github/workflows/dependabot.yml

This PR adds automatic dependency updates to Poseidon using [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates).

Add dependabot auto updates

---

configuration.example.yaml

This is based on my stupid mistake to use the name `localhost` instead of an IP address.

Specify usage of hostnames in the config

---

.github/workflows/ci.yml

This MR will ensure that we use the build cache optimally. During some investigations I figured out that the `make run` command was [very fast](https://github.com/openHPI/poseidon/runs/3862540112?check_suite_focus=true) sometimes and [a bit slower](https://github.com/openHPI/poseidon/runs/3961669088?check_suite_focus=true) in other occasions. It turns out that this behavior is linked to the automatic cache cleanup (according to the [documentation](https://pkg.go.dev/cmd/go#hdr-Build_and_test_caching)):
> The go command periodically deletes cached data that has not been used recently. After even more research, I was able to confirm that the timespan are [five days](https://github.com/golang/go/blob/d60ad1e068263832c711aaf17b6ccb1b7f71b000/src/cmd/go/internal/cache/cache.go#L255-L326).
As …

Update last trim for Go build cache

---

.github/workflows/ci.yml

This MR will use the latest versions for Go and Nomad in our GitHub actions pipeline.

Update versions used during GitHub actions

---

internal/runner/manager.go

Closes #29
... for not handling stopped Execution Environment Allocations.

Add guard close in event stream

---

api/swagger.yaml
pkg/dto/dto.go

Closes #27
The simplest solution for Issue #27 would be to make all environment variables of the system available (as implemented in this merge request).
The question remains, however, whether this is always the intention. So far, Poseidon's approach has been to make only those environment variables accessible that are declared in the execute request.
A way in between would be that only if the environment variable, e.g. "showSystemEnvironmentVariables" (or an HTTP query parameter) is set to "true", all system variables are available.

Make environment variables of the system accessible.

---

pkg/logging/logging.go
pkg/logging/logging_test.go

to allow specific error tracking in sentry. 
[See POSEIDON-F](https://sentry.io/share/issue/a943340c963747c19ce31b8611788a18/)
Otherwise all failing responses would be merged to one Sentry issue.

Change response logging message

---

Makefile

Resolves: https://github.com/openHPI/poseidon/pull/61#discussion_r762589298
The e2e test can not work until #64 is merged to the main branch.

Change the e2e test rule to use the remote image

---

internal/api/websocket.go

Closes  #49
The loop that reads the stdin notes that the client has left the connection, just before our close handler does.
Now we catch this case.

Catch the client connection "Close normal" error

---

internal/nomad/api_querier.go
internal/nomad/nomad.go

to catch the ws normal close error for all Execute requests
Resolves #44

Move the error handler to the api querier

---

internal/nomad/api_querier.go
internal/nomad/api_querier_test.go

As #44 is still not fixed, I investigated further and think we need to unwrap the error before inspecting the close cause. Hence, this MR will allow us to inspect whether the WebSocket connection was closed normally by unwrapping the error first.
Sentry:
```
error executing command in allocation: websocket closed before receiving exit code: websocket: close 1000 (normal)
```
We see at least two wrapped errors in Sentry:
Poseidon:
https://github.com/openHPI/poseidon/blob/ebbbfdb9befe98062276f4f815dc6465b7435ea5/internal/nomad/api_querier.go#L109
[Nomad](https://github.com/hashicorp/nomad/blob/e694000f4674139ab5d25607f5c8b16af3e4e0ac/api/allocations_exec.go#L206):
```go
errCh <- fmt.Errorf("websocket closed before receiving exit code: %w", err)
```
The outer one is added after the check, …

Unwrap Nomad Error for Allocation Exec

---

internal/api/websocket.go
internal/api/websocket_test.go
internal/environment/manager_test.go
internal/runner/manager_test.go
tests/constants.go

that was introduced by closing the WebSocket connection without stopping the inputLoop.
Closing #59

Fix WebSocket error

---

internal/environment/template-environment-job.hcl

This MR changes the default image used in the `template-environment-job.hcl`:
* The image previously used is not available publicly and not maintained any longer
* The new base image is not bound to any specific programming environment
The change should not have any large impact as the image is overwritten anyway. I just thought of updating this (invalid) reference.

Update default image in template-environment-job.hcl

---

docs/configuration.md
docs/resources/client.example.hcl

In order to prevent the issue mentioned in #78, an improved documentation would be helpful. Therefore, this PR adds a documentation on the dependency that needs to be added to all Nomad agents in order to enable network support.
(It's Murphy's law that each PR I open has failing unit tests, e2e tests and Trivy scan results. But why?!)

Improve documentation for Network support in Nomad

---

internal/api/websocket_test.go
internal/environment/environment.go
internal/environment/environment_test.go
internal/environment/manager.go
internal/environment/manager_test.go
internal/nomad/job.go
internal/nomad/job_test.go
internal/nomad/nomad.go
internal/nomad/nomad_test.go
internal/runner/execution_environment_mock.go
internal/runner/manager.go
internal/runner/manager_mock.go
internal/runner/manager_test.go
internal/runner/storage.go

Closes #69
Too many runners are created because the existing runners are updated. During the update, there is a short time window in which the runner is not available. Since we cannot wait completely for the update, the scaling process is already started, which, due to the runners just restarting, calculates the number of runners needed incorrectly and creates too many. By removing the update process, the cause of the miscalculation is removed.
Closes #48
We require Nomad to re-fetch the Docker image every time the environment is updated. So far, this is done by changing the jobHCL. However, we only do this once and therefore the new image is no longer loaded with the second update. By restarting the runners with each update of the execution environment, the latest Docker image is always …

Recreate runners on execution environment update

---

go.mod
go.sum

Unfortunately, the dependency gin-gonic criticised by trivy is still present in version 1.4.0 (and not 1.6.3)

Upgrade the dependencies

---

internal/nomad/nomad.go

I have added the filter for `TriggeredBy` so that not every execution produces a log statement ;) Now every failed allocation should produce two log statements as Nomad retries to place the allocation.
Closes #78

Add a warning when allocations fail

---

.github/workflows/ci.yml

This will happen if no cache is found, e.g. because it has been deleted by GitHub. A cache will be removed after seven days without usage from GitHub.
This is rather a quick fix to unblock #85 and get our pipeline green again.

Allow trim to fail

---

.github/workflows/sentry-release.yml

on every push to main.
Closes #53 
The added GitHub Action notifies Sentry about the new release and related commits.
Closes #55
The deploy/ansible-deployment (changed to [299b18](https://gitlab.hpi.de/maximilian.pass/poseidon-deployment/-/commit/299b18282520a4aa75354d5c36df2d20a113abac)) now just makes a deployment notification and not a release notification.

Run Sentry release GitHub Action

---

.github/workflows/ci.yml
internal/environment/abstract_manager.go
internal/environment/aws_environment.go
internal/environment/aws_manager.go
internal/environment/nomad_manager.go
internal/runner/abstract_manager.go
internal/runner/aws_manager.go
internal/runner/nomad_manager.go

Closes #96 
Only the field `usedRunners` contains (dynamic) information.

Add aws environments to the statistics

---

internal/api/websocket.go

This MR adds the first messages for the most detailed log level available (the TRACE level). It is intended to debug application responsiveness in case of delays within the WebSocket connection. Therefore, each WebSocket message is logged with the corresponding timestamp. 
Due to the excessive logging of raw data, this log level is not recommended for production use but rather for local development.

Add trace statements for WebSocket messages

---

configuration.example.yaml

Unfortunately, this led to two additional production Poseidon restarts.

Fix typo in configuration.example.yaml

---

deploy/aws/java11Exec/src/main/java/poseidon/SimpleMakefile.java
deploy/aws/java11Exec/src/test/java/poseidon/SimpleMakefileTest.java

Some existing Makefiles in CodeOcean still have a trailing `#exit` in recipes, which we need to ignore.
This MR is based on #118.

Ignore Comments in Makefiles starting with #

---

cmd/poseidon/main.go
deploy/grafana-dashboard/main.json
internal/api/api.go
internal/api/environments_test.go
internal/api/runners.go
internal/api/runners_test.go
internal/api/websocket.go
internal/api/websocket_test.go
internal/environment/aws_environment.go
internal/environment/nomad_environment.go
internal/environment/nomad_manager.go
internal/runner/abstract_manager.go
internal/runner/aws_manager_test.go
internal/runner/aws_runner.go
internal/runner/execution_environment.go
internal/runner/nomad_manager_test.go
internal/runner/nomad_runner.go
pkg/dto/dto.go
pkg/monitoring/influxdb2_middleware.go
pkg/storage/storage.go
pkg/storage/storage_test.go

including information about the number of requests, runner and executions and their durations.
What do you think? Is all the important information visualized? Could the structure of the dashboard be improved?
One visualization I am missing is how much time it takes Nomad to start the runners. This information can be added in the runner manager but it is not bound to a request of CodeOcean. This problem applies also for the statistics `idle_runner` and `prewarming_pool_size` - we send the same data with all incoming requests but not at the moment the change happens. That's the Prometheus way but not the Influx'... Maybe we should reconsider our decision to restrict the access to the influx client and to not provide it as singleton?!
I have no idea how to normalise the histogram.

Add Grafana Dashboard

---

go.mod
go.sum
internal/api/websocket.go
pkg/storage/storage.go

Depends on #182 
Another solution would be to avoid calling the "Delete" function multiple times. We do so [here](https://github.com/openHPI/poseidon/blob/7edd40b4f0b55d44fa2f05293098191e06b91ac2/internal/runner/nomad_manager.go#L72), [here](https://github.com/openHPI/poseidon/blob/7edd40b4f0b55d44fa2f05293098191e06b91ac2/internal/runner/nomad_manager.go#L176) and [here](https://github.com/openHPI/poseidon/blob/7edd40b4f0b55d44fa2f05293098191e06b91ac2/internal/runner/nomad_manager.go#L179).

Storage - Delete: Catch non existent removals

---

.github/workflows/ci.yml
tests/e2e/e2e_test.go

Dependabot was too fast merging #184.
We have the GitHub secret `POSEIDON_AWS_FUNCTIONS` that includes the AWS function name. This secret is provided as environment variable to the e2e tests. The added log statement shows that the e2e tests have this value.
I cannot reproduce the error in this branch and currently see no reason for this flaky behavior.

CI cannot find AWS functions

---

.github/workflows/java-ci.yml
deploy/aws/java11Exec/pom.xml

When working on #133 and #186, I noticed that we do not execute tests for our Java environment in GitHub actions. This PR adds this functionality.

Add Workflow for Java CI and specify encoding

---

internal/runner/abstract_manager.go
internal/runner/nomad_manager.go

**Monitor environment id also for deletions.**
Fixes "Check why the idle runner count always equals the prewarming pool size"
Since only **new** runners have the environment id, the others are filtered out. The **removed** runners contain the lower counts for the idle runners, these values are currently not displayed.
**Fix startup time format**
Currently the startup duration is not efficiently usable since it is stored as string with different types (second, milliseconds,..). We want the duration to be uniform.
We may need to delete all existing startup duration records as flux does not allow differing types.

Fixes for the Grafana Dashboard

---

pkg/storage/storage.go

The incorrect count is probably caused by the conversion to an uint. To determine which length leads to this high uint value we could add a logging statement.

Add storage count debug statement.

---

internal/runner/nomad_manager.go
pkg/monitoring/influxdb2_middleware.go

due to a currently not resolvable type mismatch.
See https://github.com/openHPI/poseidon/pull/188
> > Fix startup time format
> 
> According to [the official FAQ](https://docs.influxdata.com/influxdb/v2.3/reference/faq/#can-i-change-a-fields-data-type) we cannot change the type of the field afterwards. I have tried many workarounds but they do not seem to work (with our version). We could:
> 
>     * Continue saving the duration as string and convert it on query-time via [flux](https://docs.influxdata.com/flux/v0.x/stdlib/universe/duration/#convert-a-string-to-a-duration).
> 
>     * Change the fields name. Instead of `duration`, `startup_duration` for example.
> 
>     * Copy the data with the new field type into a new bucket: `poseidon_v2`
> 
> 
> Which solution would you prefer …

Change Influx field name for the startup duration

---

internal/environment/nomad_environment.go
internal/environment/nomad_manager.go
internal/environment/nomad_manager_test.go
internal/runner/abstract_manager.go

Otherwise, the new periodical events have no environment id and would not be valuable for the "idle runner" graph.

Add environment id to periodical monitoring events.

---

internal/runner/runner.go

Here, another condition that was preventing some monitoring events from having the environment and runner id as tag.

Fix missing environment id for monitoring data.

---

internal/nomad/nomad.go
internal/nomad/nomad_test.go
pkg/monitoring/influxdb2_middleware.go

when an event stream could be established once.
Closes #204 
`events.IsHeartbeat()` is false positive for error events. This way we ignored the `unexpected EOF` error that we receive when Nomad restarts.

Fix Nomad event stream is ignoring errors

---

configuration.example.yaml
docs/configuration.md
internal/config/config.go

While working on #215, I noticed that some of our config options are not correctly processed. 
- Those YML keys containing uppercase letters won't be recognised. Therefore, I changed all occurrences to lowercase letters and added some documentation.
- The `PreferServerCipherSuites` option is deprecated and ignored, as outlined in the [documentation](https://pkg.go.dev/crypto/tls#Config.PreferServerCipherSuites). I removed the config option.

Config cleanup

---

.github/workflows/ci.yml
.github/workflows/docker-image.yml
.gitignore
Makefile
api/swagger.yaml
configuration.example.yaml
deploy/e2e-test-image/Dockerfile
docs/configuration.md
internal/api/websocket_test.go
internal/config/config.go
internal/nomad/executor_api_mock.go
internal/nomad/job.go
internal/nomad/job_test.go
internal/nomad/nomad.go
internal/nomad/nomad_test.go
internal/runner/aws_runner.go
internal/runner/nomad_runner.go
internal/runner/nomad_runner_test.go
pkg/dto/dto.go
tests/e2e/runners_test.go
tests/e2e/websocket_test.go

_Part of #211 and https://github.com/openHPI/dockerfiles/pull/23, Closes #211 and closes #213, //cc @koelibri_
This PR:
- allows using a local Docker image for Development and Testing
- builds the e2e test image if modified in the current branch
- Switches the user per code execution. Unfortunately, this only works in Nomad so far (as AWS does not yet have custom images) and also imposes the first requirement on Docker images (the availability of the `/sbin/setuser` command). I would be glad to prevent the dependency on the Docker images (and the `/sbin/setuser` command) but didn't find a suitable workaround. Should we add some configuration option for this behaviour?
Open ToDos:
- Find a generalizable solution for `/sbin/setuser` dependency.
- Add AWS support.
- Refactor code to be …

#211 Start Daemons and switch user per execution

---

internal/api/runners.go
internal/nomad/api_querier.go

Related to https://github.com/openHPI/codeocean/pull/1389#discussion_r988942608
I would propose to additionally extend the `ContentLengthWriter` (a small bit) to monitor the expected content length and actual length?!

Catch context canceled error

---

Makefile

Unfortunately, with the current e2e pipeline, we are just building the final Docker image which is based on the `openhpi/docker_exec_phusion` image. In order to test with changes in the base image, we need to build that as well.
This branch tests with the latest version of the [dockerfiles](https://github.com/openHPI/dockerfiles) repository (hence the branch name) and will be merged into #240.

Rebuild base image for e2e images as well

---

Makefile
api/swagger.yaml
internal/runner/nomad_runner.go
tests/e2e/runners_test.go

by setting the sticky bit to all explicitly requested directories.
Closes #236 
This MR requires explicit requests for (protected) directories in the update file system route.

Support protected directories

---

deploy/grafana-dashboard/queries/execution-duration-hist.flux
deploy/grafana-dashboard/queries/execution-duration.flux
deploy/grafana-dashboard/queries/executions-per-minute-time.flux
deploy/grafana-dashboard/queries/executions-per-minute.flux
deploy/grafana-dashboard/queries/executions-per-runner-hist.flux
deploy/grafana-dashboard/queries/executions-per-runner.flux
deploy/grafana-dashboard/queries/idle-runner.flux
deploy/grafana-dashboard/queries/number-of-executions.flux
deploy/grafana-dashboard/queries/prewarming-pool-size.flux
deploy/grafana-dashboard/queries/request-body-size.flux
deploy/grafana-dashboard/queries/runner-per-minute.flux
deploy/grafana-dashboard/queries/runner-startup-duration.flux

by moving the stage and environment id to the front.
For the environment specific panels, the information about the stage, the environment id and the human readable image is important. I could not find another way to display those information apart concatenating them. I thought about setting the [display name](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-standard-options/) to a specific column and assumed other labels/columns would be displayed by hovering, but I could not confirm that.
To do a small readability improvement, I moved the stage and environment id information to the front.
Related to #244

Change Grafana panel label structure

---

deploy/grafana-dashboard/queries/request-latency.flux
deploy/grafana-dashboard/queries/requests-per-minute.flux
deploy/grafana-dashboard/queries/service-time.flux

by not assuming that every duration data point has a environment id tag.
Related to #244

Fix wrongly filtered data

---

cmd/poseidon/main.go
pkg/monitoring/influxdb2_middleware.go

Closes #303 
Influx was shutdown before Poseidon was terminated. In that mean time the Profiling data is written. Also in that mean time, a periodical influx event can trigger a panic since influx is already shutdown.
We implemented two changes, each fixing this scenario.

Fix panic on influx shutdown

---

internal/nomad/nomad.go
internal/nomad/nomad_test.go
internal/runner/nomad_manager.go
internal/runner/nomad_manager_test.go
pkg/monitoring/influxdb2_middleware.go

Related to #269
When deploying (Poseidon/) Nomad, we can [observe in the logs](https://github.com/openHPI/poseidon/files/10978226/syslog.suspect.poseidon.txt) that first some Nomad-specific failures occur and after that all runner get added again.
When adding the runner (again), there was no check if the runner is already in use. Therefore, the already used runner is re-added to the idleRunner. If this (/those) runner is not reassigned to another user before the runner is destroyed (e.g. due to its timeout) there is no problem. But, if the runner (A) gets re-provided to another user, another runner (B) gets started, but in the end the runner (A) will be removed just once. When trying to remove the runner (A) the second time only an error (`DeleteJob failed: job not found`) is created. In …

Fix multiple user Runner use

---

.github/codecov.yml
.github/workflows/ci.yml
.gitignore
Makefile
README.md

In addition to CodeClimate, I am adding Codecov with this PR and also [add coverage from the e2e-tests using a new feature from Go 1.20](https://go.dev/testing/coverage/).
View the latest coverage report [here](https://app.codecov.io/github/openHPI/poseidon/tree/codecov).
The advantage of Codecov is the integration with Sentry, read more about that integration [here](https://blog.sentry.io/2023/03/29/code-coverage-insights-now-in-your-stack-trace-announcing-our-codecov/). Since [Sentry acquired Codecov in November last year](https://blog.sentry.io/2022/11/30/bringing-codecov-into-the-sentry-family-where-code-coverage-meets-application-monitoring/), I would assume more interesting integrations will arrive.
Once we are satisfied with Codecov, we could remove the CodeClimate integration.

Add Codecov integration

---

internal/api/api.go
internal/api/auth/auth.go
internal/api/environments.go
internal/api/helpers.go
internal/api/runners.go
internal/api/websocket.go
internal/api/ws/codeocean_reader.go
internal/api/ws/codeocean_writer.go
internal/api/ws/codeocean_writer_test.go
internal/nomad/api_querier.go
internal/nomad/nomad.go
internal/nomad/sentry_debug_writer.go
internal/runner/aws_runner.go
internal/runner/nomad_manager.go
internal/runner/nomad_runner.go
pkg/logging/logging.go
pkg/logging/sentry_hook.go
pkg/monitoring/influxdb2_middleware.go
pkg/nullio/ls2json.go

Closes #326 
With updating our Sentry Hook, tracing information stored in the passed context can be associated with sentry events/issues.
With this first commit, we added the context just to log statements where an context was available. In many places we do not pass the (request) context. I think it would be a good practice to do so in the future, (not only) because we then could associate Sentry issues with Sentry Traces. We may use this PR for a refactoring into the direction of more context passing.
I noticed, that Sentry developed [its own Logrus Hook](https://github.com/getsentry/sentry-go/blob/master/logrus/logrusentry.go) 4 months ago. We may think about switching to that. At this moment their implementation does not support the tracing association but there is an open PR …

Add context to Sentry Hook

---

internal/nomad/sentry_debug_writer.go

Closes #354
In order to guarantee the order of the debug messages, we can handle the debug messages synchronous to the Write calls, as we expect the write calls to be in the right order.
We may even remove the Mutex?!

Synchronize Sentry debug message handling.

---

internal/nomad/nomad.go
pkg/monitoring/influxdb2_middleware.go

Related to #358 and #357 
In order to combine the monitoring information with the Poseidon logs we need to identify the allocation transactions with its job ID (and not only its allocation ID).

Add Job ID to Nomad Allocation monitoring.

---

internal/nomad/api_querier.go
internal/nomad/nomad.go
pkg/monitoring/influxdb2_middleware.go

and send all Nomad events to Influxdb.
In https://github.com/openHPI/poseidon/issues/358#issuecomment-1537218034 we assumed the handling of the Nomad events cause #358. In order to verify and fix this issue, we need to verify which events we (don't) get. In order not to flood the Poseidon log, we dump those events to Influxdb in the hope that it can handle that.. What do you think?

Monitor the Nomad events

---

internal/nomad/nomad.go
pkg/monitoring/influxdb2_middleware.go

It would also be great to see the client status in the monitoring data. Sorry for putting this in a separate PR :sweat_smile:

Add Client Status to Nomad Allocation monitoring.

---

internal/nomad/nomad.go
internal/nomad/nomad_test.go

Related to #358 
The idle runner decrease from time to time as the Nomad event `AllocationUpdated` with the status `pending` is common but not always send and our process relied on it.
Automatic merge and deployment this night.

Fix missing idle runners.

---

internal/nomad/api_querier.go
internal/nomad/nomad.go

and add time to Nomad event monitoring.
Related to #358 
If we think about refactoring the Nomad event handling to listen to the `Job` event sometime, we should use the current situation, to collect some data about those events.

Monitor Job events

---

internal/environment/nomad_environment.go
internal/environment/nomad_environment_test.go

by checking the number of required runners before creating an additional runner.

Fix increased prewarming pool size

---

internal/runner/nomad_manager.go
internal/runner/nomad_manager_test.go

Related to #358 
Currently we observe some runners being `OOM Killed` (just) in the Poseidon logs (Lack of Error reporting or ok?). This leads to the runner being restarted and added to the idle runners again (even if it was used before the restart). In this case [POSEIDON-2N ](https://codeocean.sentry.io/issues/4220082532)`Too many idle runner` is expected for each restarted and re-added runner.
In this process we could identify two weaknesses:
1. We observed that the WebSocket connections for in that moment running executions are not directly stopped but ran into the execution timeout (of 30 seconds). In these 30 seconds much could happen. I.e. the runner gets restarted, re-added to the idle runners, and re-assigned to another user. When the WebSocket connection the got cancelled (due …

Fix decreased prewarming pool due to inactivity timer

---

internal/nomad/sentry_debug_writer.go

to verify that the date command is sometimes returning an empty string with exit code 5.
Related to #325

Insert debug message into execution tracing

---

internal/api/ws/codeocean_writer.go
internal/runner/nomad_manager.go
internal/runner/nomad_runner.go

and ignore expected reasons such when the runner got destroyed by an API request.
As we have seen with [`POSEIDON-2Y`](https://codeocean.sentry.io/issues/4330986806), we are logging that `the client wants to stop the runner`. This is a false positive warning. With this PR we filter these reasons from throwing a warning.

Refactor Runner Destroy Reason Masking

---

cmd/poseidon/main.go
cmd/poseidon/main_test.go
internal/environment/nomad_environment.go
internal/environment/nomad_environment_test.go
internal/environment/nomad_manager.go
internal/environment/nomad_manager_test.go
internal/runner/nomad_manager.go
internal/runner/nomad_runner.go
pkg/util/util.go

Closes #408 
The retry is blocking as (1) we require a proper Nomad connection for Poseidon to work and (2) we would risk doubling the number of idle runner when an external request creates an environment before we have recovered it.

Retry Environment Recovery

---

internal/runner/nomad_runner.go
internal/runner/nomad_runner_test.go
pkg/util/merge_context.go
pkg/util/merge_context_test.go

Merge Context

---

pkg/util/merge_context.go

Related to #429; Already deployed
The now removed statement of sending an empty struct into the channel blocked the goroutine until the channel of Done got listened for. This led to a goroutine leak as one does not necessarily has to call the Done function of a context.
We fix this issue by removing this value. It was unnecessary anyway as a closed channel always returns the null-value of the returned type.

Fix Memory Leak caused by the merge_context.

---

internal/nomad/nomad.go
internal/nomad/nomad_test.go

In the recent host migration, different Nomad hosts got restarted. This PR handles the case of runner `29-6f04b525-5315-11ee-af32-fa163e079f19`. What happens in its [Poseidon Log](https://github.com/openHPI/poseidon/files/12643314/poseidonLog.txt) is documented in the test case `TestHandleAllocationEvent_RegressionTest_14_09_2023`.
In summary, multiple consecutive reschedulings led again (such as in #433) to the wrong triggering of the race condition handling. As this handling (introduced in f031219cb8cd02f289abb4d107396fd7457a69f6) already caused multiple bugs and its purpose seems to be just to suppress incorrect warnings in case of a race condition, I replaced it with an implementation that does not influence the process.

Fix the recent event of lost runners

---

api/websocket.schema.json

by changing the `required` attribute to be an array as described in [the official documentation](https://json-schema.org/understanding-json-schema/reference/object.html#required).

Fix WebSocket JSON schema

---

cmd/poseidon/main.go

that alerts and prints additional debug information in case Poseidon exceeds 1 GB of memory usage.
Related to #453

Introduce debug memory monitoring

---

internal/nomad/nomad_test.go
internal/runner/nomad_manager_test.go
internal/runner/nomad_runner_test.go
tests/util.go

Closes #494
- Flaky behavior could not be reproduced
- Flaky behavior could not be reproduced
- Flaky behavior could not be reproduced
- Flaky behavior could not be reproduced

Fix flaky unit tests

---

internal/api/runners.go
pkg/monitoring/influxdb2_middleware.go

of errors trying to read the request body.
This is okay, as those errors indicate an issue with the client (CodeOcean) or the network, and we do not like to track those issues in the context of Poseidon.
Closes #467

Decrease Log Severity

---

cmd/poseidon/main.go
cmd/poseidon/main_test.go
go.mod

Remove deprecated `syscall` dependency.

---

internal/nomad/nomad.go

for measuring the performance of the until loop of the stderr connection.
Closes #442
Accidentally, I pushed this commit directly to `main`.  
In response, I reverted that commit on `main` and enabled the branch protection rule `Do not allow bypassing the above settings`.

Inject Execution Debug Message

---

pkg/monitoring/influxdb2_middleware.go

as we have experienced silent package drops. This issue is not fixed, it is just made less probable.
Closes #479

Adjust Influxdb buffering

---

pkg/monitoring/influxdb2_middleware.go

With #451, we found that writing an InfluxDB data point might block and lead to high latencies.
Implements "Issue" 1 of https://github.com/openHPI/poseidon/issues/541#issuecomment-1912579294

Decouple InfluxDB writings from request handling.

---

internal/api/api.go
internal/api/environments.go
internal/config/config.go

by replacing the length check with a string comparison. This rule was introduced with the new GolangCI lint version.

Fix linter emptyStringTest rule

---

cmd/poseidon/main.go

Otherwise, the health checks would fail:
```
level=debug msg="Failed watchdog health check" error="Get \"https://[::]:7200/api/v1/health\": tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, ::1, not ::" package=main
```

Replace IPv6 unspecified address for watchdog health checks

---

configuration.example.yaml
internal/config/config.go
internal/environment/nomad_environment.go
internal/environment/nomad_environment_test.go

Closes #490 
The failing DNS resolution was caused by Nomad overwriting the DNS configuration of Docker and the CNI secure bridge. To set valid Nameservers, we have to configure the according Nomad options.

Fix Runner DNS resolution

---

internal/nomad/nomad.go
internal/nomad/nomad_test.go

in the Nomad `evaluations` map by replacing the simple map with our concurrency-ready storage object.
Closes #573

Fix concurrent map write

---

.golangci.yaml
cmd/poseidon/main.go
internal/config/config.go
internal/runner/nomad_runner.go
tests/constants.go
tests/e2e/e2e_helpers.go

Open to discussion: By specifying the linters explicitly in an allow list, we are missing all the linters that are added in each release. Should we drop the allow list and introduce a deny list if necessary?

Fix Golangci-lint configuration

---

internal/environment/template-environment-job.hcl

Related to #587 
Fix restart and reschedule configuration to not reschedule infinitely (e.g. due to an invalid image specifier).
ToDo:

Nomad Restart and Reschedule Policy

---

internal/nomad/nomad.go

that was caused by Nomad sending similar evaluation information multiple times and Poseidon closing the response channel only asynchronously.
Closes #618

Fix Nomad evaluation race condition

---

internal/api/runners.go
internal/nomad/api_querier.go

to be able to differentiate between the different errors that occur.
Closes #619

Refine updateFileSystem logging messages

---

internal/api/runners.go
internal/nomad/api_querier.go

by throwing the log warning at the common level of the Execute call and not at multiple places relying on it.
Related to #589

Group Sentry issues

---

pkg/logging/context_hook.go
pkg/logging/logging_test.go
pkg/logging/sentry_hook.go

that led to errors being duplicated in the following events sharing the same scope.
Now, every event has its own local scope.
Closes #628

Fix Sentry Hook Global Scope

---

internal/api/runners.go
pkg/nullio/content_length.go
tests/e2e/runners_test.go

- The `Content-Length`-Header did not get removed in the error handling
- The Content-Length Writer fired the HTTP Headers unnecessarily early impeding sending of an error message.
Closes #595

Fix Content Length Writer

---

internal/nomad/api_querier.go
pkg/logging/sentry_hook.go

by fixing the usage of the wrong context, thus, adding an entry in Sentry's Stack trace. Also, we added a comment referencing the upstream issue regarding the unexpected EOF error.
Related to #641

Refactor Unexpected EOF Sentry handling

---

.github/dependabot.yml

Within this repo, we also have a few Dockerfiles that could deserve updates.

Enable Dependabot for Docker

---

internal/runner/nomad_runner.go

The new minor update of Golangcilint, from v1.60.2 to v1.60.3 enabled the identification of another theoretical Integer Overflow Vulnerability.
Related to #664

Follow up, Fix Integer Overflow

---

.golangci.yaml
go.mod
go.sum

Since release 1.23, Go will automatically download a newer toolchain, if available. Hence, we don't need to specify a patch version ourselves.
Checklist from the issue:
Fixes #648

Update Golang from 1.22 to 1.23

---

internal/runner/nomad_runner.go
pkg/nullio/ls2json.go
tests/e2e/runners_test.go

for listing the file system with a link, the executing user does not have enough privileges to read the target.
Closes #596

Fix missing link target

---

internal/runner/nomad_manager.go
internal/runner/nomad_manager_test.go
internal/runner/nomad_runner.go
internal/runner/nomad_runner_test.go

by now just updating the port mapping.
Closes #651

Fix runner replacement on recovery

---

internal/runner/inactivity_timer_test.go
tests/util.go

Closes #669 
There was a race condition between both channels in `ChannelReceivesSomething` having data.
The reason why this race condition appears only now is likely that the small delay of `<-time.After(0)` got reduced with [the timer refactoring of Go 1.23](https://go.dev/doc/go1.23#timer-changes).

Fix flaky inactivity timer test

---

Makefile

that now represents the default behavior [[1]](https://pkg.go.dev/cmd/go/internal/get).
The deprecation warning shows up when running `make test`.

Remove deprecated go get -d flag

---

internal/nomad/event_stream_handling_test.go
internal/nomad/nomad.go

by not purging a job once its allocation stops (and maybe would be replaced).
Related to #673 
Scenario: Deleting and Creating the environment before each restart
Before PR
1 - 0/5
2 - 0/5
3 - 0/5
4 - 0/5
5 - 0/5
After PR
1 - 5/5
2 - 5/5
3 - 5/5 (one slow recreation)
4 - 5/5
5 - 5/5

Fix prohibiting Nomad Job recreation with delay in between

---

internal/environment/template-environment-job.hcl

by increasing the memory reservation per runner.
Closes #676 
This may not be the most stable solution as different environments (images) might require different amounts of memory. However, with increasing the memory reservation per runner only as many runners are allocated on the agent as it could handle right now (with the given server resources, and the allocation definition).

Fix OOM Killing Nomad Agent

---

docs/nomad_usage.md

to describe the behavior of running executions during Nomad restarts.
Related to #651

Improve Nomad Docs

---

internal/nomad/event_stream_handling.go
internal/nomad/event_stream_handling_test.go
internal/nomad/nomad.go
pkg/monitoring/influxdb2_middleware.go

for more reliant event handling.
In recent cases, we have observed Nomad not sending Allocation-stopping events but just JobDeregistered events. We add a handling of those to capture also these cases.
Closes #649

Add Nomad Job Event Handling

---

internal/environment/nomad_environment.go
internal/nomad/command_execution.go
internal/runner/aws_runner_test.go
internal/runner/nomad_manager.go
internal/runner/nomad_manager_test.go
internal/runner/nomad_runner.go
pkg/monitoring/influxdb2_middleware.go
pkg/util/util.go

[Some reference](https://dev.to/ccoveille/about-the-gosec-g115-drama-or-how-i-faced-back-integer-conversion-overflow-in-go-1302)

Fix Golangci Lint v1.61

---

internal/runner/nomad_manager.go
internal/runner/nomad_manager_test.go

"Environment stopped unexpectedly," which also got triggered by migrations.
Related to #672

Restrict false positive warning

---

internal/runner/nomad_manager_test.go

by giving Poseidon more time to cancel the execution before destroying the runner.
Closes #692

Fix flaky TestNomadRunnerManager_Load unit test

---

cmd/poseidon/main.go
internal/api/environments.go
internal/environment/abstract_manager.go
internal/runner/abstract_manager.go
internal/runner/nomad_manager.go
internal/runner/nomad_manager_test.go

If only AWS was enabled, a 500 error instead of a 404 error was returned. If both Nomad and AWS was disabled, the requests returned with a 200 response but an empty body. A silent nil-dereference was triggered.
Closes https://github.com/orgs/openHPI/projects/4/views/1?pane=issue&itemId=81052193

Fix provideRunner with no managers enabled.

---

deploy/aws/java11Exec/src/main/java/poseidon/SimpleMakefile.java
deploy/aws/java11Exec/src/test/java/poseidon/AppTest.java
deploy/aws/java11Exec/src/test/java/poseidon/SimpleMakefileTest.java

Previously, a command such as the following would fail due to the additional quotes used:
```shell
env CODEOCEAN=true /bin/bash -c "unset \"\${!AWS@}\" && make test CLASS_NAME=\"HalloWeltTest2\" FILENAME=\"HalloWeltTest2.java\""
```

AWS: Fix SimpleMakefile when command is wrapped

---

.github/workflows/ci.yml
.github/workflows/resources/poseidon-minimal.service
configuration.example.yaml
docs/configuration.md
docs/nomad_usage.md

As systemd is a fixed term, we stick to the official spelling with a lowercase s.

Unify spelling of systemd

---

internal/runner/aws_runner.go

Previously, the data was logged as bytes, which required an additional converter to read them.

AWS: Show request data as plain text

---

deploy/aws/java11Exec/src/main/java/poseidon/App.java

Since the `CLASSPATH` is not set already, the previous solution created the following path:
```java
".:/var/task/lib/org.hamcrest.hamcrest-3.0.jar:/var/task/lib/junit.junit-4.13.2.jar:null"
```
Now, we create the following:
```java
".:/var/task/lib/org.hamcrest.hamcrest-3.0.jar:/var/task/lib/junit.junit-4.13.2.jar"
```

AWS: Fix CLASSPATH to prevent NULL entry

---

deploy/aws/java11Exec/pom.xml
deploy/aws/java11Exec/src/main/java/poseidon/App.java
deploy/aws/java11Exec/src/main/java/resources/log4j2.xml

The previous SDK used has been deprecated. As part of this change, we also need to include Log4J explicitly.
https://aws.amazon.com/de/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/

Update AWS SDK to v2

---

internal/api/runners.go

AWS won't support listing the file system. However, since CodeOcean calls the method for each runner, this would yield an error every time. We want to avoid these errors and hence just handle this more gracefully.

AWS: Properly handle requests to list the file system

---

.github/workflows/java-ci.yml

Similar to the Python CI, we only want to execute tests when a corresponding file changed. This will save unnecessary resources.

Limit Java CI to relevant changes

---

.github/workflows/aws-deploy.yml
docs/aws_deployment.md
docs/resources/aws-role.json5

I've tested the pipeline and permissions multiple times and am confident it works reliably. Following AWS recommendations, a dedicated user account with minimal privileges is used for this deployment process.

Add AWS deploy using GitHub Actions
